creacion componente: controllers, route y models
EP-2024C2/tp-ntom-fsociety404 pull request #14
Opened 2024-10-07 23:22 UTC by jblenis

2024-10-07 23:28 UTC, mnunez-unahur requested changes

2024-10-07 23:28 UTC, mnunez-unahur commented on src/controllers/componente_controllers.js
> +        return res.status(404).json({ error: 'Fabricante no encontrado' });
debería ser "Componente no encontrado"?

2024-10-07 23:28 UTC, mnunez-unahur commented on src/controllers/componente_controllers.js
> +        res.status(500).json({error : `error al intentar crear: "${error}"`})
el mensaje deberia ser "error al intentar actualizar componente" ?

2024-10-08 02:03 UTC, jblenis commented on src/controllers/componente_controllers.js
> +        return res.status(404).json({ error: 'Fabricante no encontrado' });
resuelto!

2024-10-08 02:04 UTC, jblenis commented on src/controllers/componente_controllers.js
> +        res.status(500).json({error : `error al intentar crear: "${error}"`})
resuelto!

2024-10-09 20:07 UTC, merged